### ISSUE TITLE
Is every business domain expected to create a spec for interop within that domain?

### ISSUE THREAD

**Issue by elf-pavlik** [solid/chat#1]
In [Solid Application Interoperability](https://solid.github.io/data-interoperability-panel/specification/) we don't expect every domain to need its own domain-specific specification. Interop pretty much depends on domain-agnostic SAI spec and domain-specific [ShapeTrees](https://shapetrees.org/) (which in turn depends on data shapes).

**Comment by woutermont** [comment]
Good to point this out. Indeed, Solid should not create domain-specific models/specs. Interoperability (client-client) is provided in a way that third parties can define and agree on such models using shapes, shape trees, service descriptions etc.

**Comment by timbl** [comment]
Yes, every domain has to typically make is own spec for its own applications.  If tools like shapes or SAI or shapetrees make that easier then they can use that.  But in most domains by far the need is to map existing non-solid standards into linked data in Solid pods so that data can imported, exported and ideally synced with external systems.    Existing well used standards like VCARD, iCALENDAR, OFX, GPX, FHIR, and hey for chat Matrix, involve typically a lot of work to build consensus and have a lot  of value.   Making the most straightforward mapping is important.

**Comment by woutermont** [comment]
@timbl, I agree that these mappings are important. What I want to point out is that specific mappings are not within the scope of Solid. 

I also believe that we will not necessarily need elaborate specifications to achieve these mappings. As long as we have generic mechanisms like SAI built into Solid, all it takes for interop is for popular shapes to evolve organically. Specification-based approaches are of course still possible, but should hook into such mechanisms, rather than exist separate from them.

**Comment by elf-pavlik** [comment]
I'm afraid that we might be splitting the conversation between this issue and https://github.com/solid/specification/issues/553

I also would be cautious with taking positions of either agreeing or disagreeing before we are able to understand what exactly is being proposed. This repo has a minimal README and this one issue.

I would even lean toward closing this issue or transferring it to the specification repo, converting into a discussion and using it as a general problem discussion while the https://github.com/solid/specification/issues/553 would serve as a specific proposal falling under that general theme.

**Comment by woutermont** [comment]
I created a [discussion](https://github.com/solid/specification/discussions/554) in [solid/specification](https://github.com/solid/specification/) to go into this on a more general level, quoting @elf-pavlik and @timbl's comments. i agree with closing this for clarity.

**Comment by timbl** [comment]
Now you have the discussion, which is general, could you close this issue which specifically on chat?
